export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Новая задача",
    date: "01.11.23",
    status: "Нужно сделать",
  },
  {
    id: 3,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 4,
    topic: "Research",
    title: "Новая задача",
    date: "01.11.23",
    status: "Нужно сделать",
  },
  {
    id: 5,
    topic: "Web Design",
    title: "Сделать верстку",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 6,
    topic: "Research",
    title: "Анализ конкурентов",
    date: "01.11.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Дизайн модалки",
    date: "04.11.23",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Copywriting",
    title: "Текст для лендинга",
    date: "10.11.23",
    status: "Тестирование",
  },
  {
    id: 9,
    topic: "Web Design",
    title: "Финальная правка",
    date: "15.11.23",
    status: "Готово",
  },
  {
    id: 10,
    topic: "Research",
    title: "Сбор отзывов",
    date: "01.12.23",
    status: "Без статуса",
  },
];